# Generated by Django 3.0 on 2020-01-26 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=11, null=True)),
                ('qtd_quartos', models.CharField(max_length=2, null=True)),
                ('conservacao', models.CharField(max_length=3, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ativacao', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='imoveis')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
